---
kind: pipeline
name: omeka:4.1.1 php:8.2 mariadb:10.5 cypress
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.5
  name: db
- image: giocomai/omeka-s-docker:v4.1.1
  name: omekas
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: omeka_test
    MYSQL_HOST: db
steps:
- commands:
  - bash -c "npx cypress run || base64 -w0 'cypress/screenshots/necropolis.cy.js/Necropolis test -- Loads the website (failed).png' || base64 -w0 'cypress/screenshots/necropolis.cy.js/Necropolis test -- Tests Necropolis (failed).png' && false"
  image: cypress/included
  name: cypress
workspace:
  path: /var/www/html/modules/Necropolis
---
kind: signature
hmac: b6bbd94e7d1e40079e546386dca31b3ccc87b0439d315261be5a7b950415b7d2

...
