<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'title'
    ],
    [
        'label' => $translate('Deleted'),
        'value' => 'deleted'
    ],
];
?>

<?php echo $this->pageTitle($translate('Deleted items')); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>

<?php if ($items): ?>
    <?php echo $this->partial('necropolis/partial/resource-table', ['resources' => $items]); ?>

    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
    </div>
<?php else: ?>
    <div class="no-resources">
        <p><?php echo $translate('Omeka could not find any items.'); ?></p>
    </div>
<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>

