<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Deleted'); ?></th>
            <th><?php echo $this->translate('Deleted by'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resources as $resource): ?>
            <?php $deleter = $resource->deleter(); ?>
            <tr>
                <td><?php echo $resource->displayTitle(); ?></td>
                <td><?php echo $this->i18n()->dateFormat($resource->deleted(), 'medium', 'medium'); ?></td>
                <td><?php echo $deleter ? $deleter->link($deleter->email() . ' (' . $deleter->name() . ')') : $this->translate('[Deleted user]'); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
